version: 2.1
jobs:
  push:
   docker:
      - image: ubuntu:18.04
   steps:
      - run:
          name: init
          command: |
           apt-get -y update && apt-get -y upgrade && apt-get -y install python3 git curl wget repo python3-pip
           pip3 install python-telegram
           git config --global user.name "Giovix92"
           git config --global user.email "ggualtierone@gmail.com"
           git config --global color.ui false
           git clone https://github.com/Giovix92/ota_scripts
           . ota_scripts/push.sh
workflows:
  version: 2.1
  cooking:
    jobs:
      - push
